Sesi 1

In [ ]:
print("hello world ")

hello world 


In [ ]:
import time

In [ ]:
print("Tanggal dan waktu : ", time.ctime())

Tanggal dan waktu :  Fri Feb  7 03:48:50 2025


In [ ]:
z = "hello"
y = 12
c = 32.3
f = ["apple", "banana", "berry"]

z, y, c, f
print(z, y, c, f)

hello 12 32.3 ['apple', 'banana', 'berry']


In [ ]:
o = int(1)
y = int(2.8)
z = int("3")
j = str(20)

print(o, y, z, j)

1 2 3 20


In [ ]:
a = "hello"
b = " world"
c = a + b
print(c)

hello world


In [ ]:
a = "hello world"
print(a[len(a)-1])
print(len(a))


d
11


In [ ]:
b = "Binus Univerity"
print(b[2:5])

c = "Binus Univ"
print(c[3])

d = "Binus Univ"
print(d[2:len(d)])

nus
u
nus Univ


In [ ]:
a = "hello"
print(a.upper())

b = "hello"
print(b.lower())

c = "hello"
print(c.replace("l", "x"))

HELLO
hello
hexxo


In [ ]:
nama = "arya"
x = 19
string = "nama saya {} umur {}"
print(string.format(nama, x))

nama saya arya umur 19


In [ ]:
nama = "grace"
for i in enumerate(nama):
  print(i)

(0, 'g')
(1, 'r')
(2, 'a')
(3, 'c')
(4, 'e')


In [ ]:
def perbandingan(a,b):
  if a>b:
    print("a lebih dari b")
  elif a<b:
    print("a kurang dari b")
  else:
    print("a = b")

In [ ]:
perbandingan(2,4)

a kurang dari b


In [ ]:
i = 1
while i < 6:
  print(i)
  i += 1

1
2
3
4
5


In [ ]:
i = 2
for i in range(i, 6):
  print(i)

2
3
4
5


In [ ]:
for x in range(2, 40):
  if x % 2 == 0:
    print(x, "genap")
  else:
    print(x, "ganjil")

2 genap
3 ganjil
4 genap
5 ganjil
6 genap
7 ganjil
8 genap
9 ganjil
10 genap
11 ganjil
12 genap
13 ganjil
14 genap
15 ganjil
16 genap
17 ganjil
18 genap
19 ganjil
20 genap
21 ganjil
22 genap
23 ganjil
24 genap
25 ganjil
26 genap
27 ganjil
28 genap
29 ganjil
30 genap
31 ganjil
32 genap
33 ganjil
34 genap
35 ganjil
36 genap
37 ganjil
38 genap
39 ganjil


In [ ]:
import numpy as np

In [ ]:
x = np.array([[1, 2, 3], [3, 6, 7]])
x


array([[1, 2, 3],
       [3, 6, 7]])

In [ ]:
y = np.array([[8, 2, 9], [3, 5, 7]])
x + y

array([[ 9,  4, 12],
       [ 6, 11, 14]])

In [ ]:
print(x+y)

[[ 9  4 12]
 [ 6 11 14]]


In [ ]:
data = np.array([10, 9, 8 ,7, 5, 6])

print("rata-rata: ", np.mean(data))
print("maksimum: ", np.max(data))
print("minimum: ", np.min(data))
print("standar deviasi", np.std(data))

rata-rata:  7.5
maksimum:  10
minimum:  5
standar deviasi 1.707825127659933


In [41]:

user = input("masukkan username anda: ")
pas = input("masukkan password anda: ")
while pas != "Admin123":
  print("password salah")
  pas = input("masukkan password: ")
print("Login Berhasil, Selamat datang ", user)

print("\n")

Name = input("Masukan nama siswa : " )
UAS = float(input("Masukan Nilai UAS : "))
while UAS > 100 or UAS < 0:
  print("Invalid Input")
  UAS = float(input("Masukan Nilai UAS : "))
UTS = float(input("Masukan Nilai UTS : "))
while UTS > 100 or UTS < 0:
  print("Invalid Input")
  UTS = float(input("Masukan Nilai UTS : "))
ASG = float(input("Masukan Nilai Assigment : "))
while ASG > 100 or ASG <0:
  print("Invalid Input")
  ASG = float(input("Masukan Nilai Assigment : "))

Final = (UAS * 0.5) + (UTS * 0.3) + (ASG * 0.2)

if Final <= 11:
  Grade = "F"
elif Final <= 59:
  Grade = "E"
elif Final <= 64:
  Grade = "D"
elif Final <= 69:
  Grade = "C"
elif Final <= 74:
  Grade = "B-"
elif Final <= 79:
  Grade = "B"
elif Final <= 84:
  Grade = "B+"
elif Final <= 89:
  Grade = "A-"
elif Final <= 100:
  Grade = "A"

print("=================================================")
print("Hasil perolehan nilai", Name)
print("Final Score:", Final)
print("Grade ", Grade)

masukkan username anda: ASarya
masukkan password anda: Admin123
Login Berhasil, Selamat datang  ASarya


Masukan nama siswa : Asarya
Masukan Nilai UAS : 23
Masukan Nilai UTS : 73
Masukan Nilai Assigment : 50
Hasil perolehan nilai Asarya
Final Score: 43.4
Grade  E
